export const SKILLS_ROOT = '~/.agent-tools/skills'
export const AGENTS_ROOT = '~/.agent-tools/agents'
export const CENTRALIZE_SKILL_ROOT = '~/.agent-tools/skills'
export const CENTRALIZE_CONFIG_PATH = '~/.agent-tools/skills/centralize-skills/config.yaml'
export const CENTRALIZE_SCRIPTS_ROOT = '~/.agent-tools/skills/centralize-skills/scripts'
